version: '3.8'
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: novel_be
    env_file:
      - ./backend/.env 
    restart: always
    ports:
      - "8080:8080"
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:8080/actuator/health || exit 1" ]
      interval: 1s
      retries: 5
      start_period: 2s

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: novel_fe
    restart: always
    ports:
      - "4200:80"
    depends_on:
      backend:
        condition: service_healthy

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

volumes:
  redis_data:
    driver: local
