services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: novel_be
    env_file:
      - ./backend/.env # Ensure this file exists in the same directory as docker-compose.yml
    restart: always
    ports:
      - "8080:8080"
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:8080/actuator/health || exit 1" ]
      interval: 1s
      retries: 5
      start_period: 2s

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: novel_fe
    restart: always
    ports:
      - "4200:80"
    depends_on:
      backend:
        condition: service_healthy
