apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.36.0 (ae2a39403)
  labels:
    io.kompose.service: backend
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: backend
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.36.0 (ae2a39403)
      labels:
        io.kompose.service: backend
    spec:
      containers:
        - env:
            - name: DATABASE_PASSWORD
              value: novel_password
            - name: DATABASE_URL
              value: jdbc:postgresql://postgres:5432/novel_db
            - name: DATABASE_USERNAME
              value: novel_user
            - name: RABBITMQ_HOST
              value: rabbitmq
            - name: RABBITMQ_PORT
              value: "5672"
            - name: SPRING_PROFILES_ACTIVE
              value: docker
          image: backend:latest
          name: backend
          ports:
            - containerPort: 8081
              protocol: TCP
      restartPolicy: Always
