apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.36.0 (ae2a39403)
  labels:
    io.kompose.service: kibana
  name: kibana
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: kibana
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.36.0 (ae2a39403)
      labels:
        io.kompose.service: kibana
    spec:
      containers:
        - env:
            - name: ELASTICSEARCH_HOSTS
              value: http://elasticsearch:9200
            - name: XPACK_SECURITY_ENABLED
              value: "false"
          image: docker.elastic.co/kibana/kibana:8.10.2
          livenessProbe:
            exec:
              command:
                - curl -f http://localhost:5601/api/status || exit 1
            failureThreshold: 5
            periodSeconds: 10
          name: kibana
          ports:
            - containerPort: 5601
              protocol: TCP
      restartPolicy: Always
