apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.36.0 (ae2a39403)
  labels:
    io.kompose.service: kibana
  name: kibana
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: kibana
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.36.0 (ae2a39403)
      labels:
        io.kompose.service: kibana
    spec:
      initContainers:
        - name: wait-for-elasticsearch
          image: curlimages/curl:7.83.1
          command: ['sh', '-c', 'until curl -s -f http://elasticsearch:9200/_cluster/health; do echo waiting for elasticsearch; sleep 2; done;']
      containers:
        - env:
            - name: ELASTICSEARCH_HOSTS
              value: http://elasticsearch:9200
            - name: XPACK_SECURITY_ENABLED
              value: "false"
          image: docker.elastic.co/kibana/kibana:8.10.2
          livenessProbe:
            httpGet:
              path: /api/status
              port: 5601
            initialDelaySeconds: 90
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 5
          name: kibana
          ports:
            - containerPort: 5601
              protocol: TCP
          resources:
            requests:
              memory: "512Mi"
              cpu: "500m"
            limits:
              memory: "1Gi"
              cpu: "1000m"
      restartPolicy: Always