apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.36.0 (ae2a39403)
  labels:
    io.kompose.service: logstash
  name: logstash
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: logstash
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.36.0 (ae2a39403)
      labels:
        io.kompose.service: logstash
    spec:
      initContainers:
        - name: wait-for-elasticsearch
          image: curlimages/curl:7.83.1
          command: ['sh', '-c', 'until curl -s -f http://elasticsearch:9200/_cluster/health; do echo waiting for elasticsearch; sleep 2; done;']
      containers:
        - env:
            - name: LS_JAVA_OPTS
              value: -Xmx512m -Xms512m  # Increase memory
          image: docker.elastic.co/logstash/logstash:8.10.2
          livenessProbe:
            httpGet:
              path: /_node/pipelines
              port: 9600
            initialDelaySeconds: 90
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 5
          name: logstash
          ports:
            - containerPort: 5044
              protocol: TCP
            - containerPort: 5000
              protocol: TCP
          volumeMounts:
            - mountPath: /usr/share/logstash/pipeline
              name: logstash-cm0
              readOnly: true
          resources:
            requests:
              memory: "512Mi"
              cpu: "500m"
            limits:
              memory: "1Gi"
              cpu: "1000m"
      restartPolicy: Always
      volumes:
        - configMap:
            name: logstash-cm0
          name: logstash-cm0