apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.36.0 (ae2a39403)
  labels:
    io.kompose.service: logstash
  name: logstash
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: logstash
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.36.0 (ae2a39403)
      labels:
        io.kompose.service: logstash
    spec:
      containers:
        - env:
            - name: LS_JAVA_OPTS
              value: -Xmx256m -Xms256m
          image: docker.elastic.co/logstash/logstash:8.10.2
          livenessProbe:
            exec:
              command:
                - curl -f http://localhost:9600/_node/pipelines?pretty || exit 1
            failureThreshold: 5
            periodSeconds: 10
          name: logstash
          ports:
            - containerPort: 5044
              protocol: TCP
            - containerPort: 5000
              protocol: TCP
          volumeMounts:
            - mountPath: /usr/share/logstash/pipeline
              name: logstash-cm0
              readOnly: true
      restartPolicy: Always
      volumes:
        - configMap:
            name: logstash-cm0
          name: logstash-cm0
